-- MySQL Script generated by MySQL Workbench
-- Sat May 17 12:13:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `dtNasc` DATE NULL,
  `email` VARCHAR(200) NULL,
  `senha` VARCHAR(100) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `idpost` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `conteudo` VARCHAR(600) NULL,
  `imagem` TEXT NULL,
  `status` ENUM('ativo', 'inativo', 'em análise') NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_post_usuario_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_post_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`denuncia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`denuncia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`denuncia` (
  `iddenuncia` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `descricao` VARCHAR(50) NULL,
  `idpost` INT NOT NULL,
  `status` ENUM('pendente', 'avaliada', 'ignorada') NULL,
  PRIMARY KEY (`iddenuncia`, `idusuario`),
  INDEX `fk_denuncia_usuario1_idx` (`idusuario` ASC) VISIBLE,
  INDEX `fk_denuncia_post1_idx` (`idpost` ASC) VISIBLE,
  CONSTRAINT `fk_denuncia_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denuncia_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `mydb`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`favoritos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`favoritos` (
  `idfavorito` INT NOT NULL,
  `idpost` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idfavorito`),
  INDEX `fk_favoritos_post1_idx` (`idpost` ASC) VISIBLE,
  INDEX `fk_favoritos_usuario1_idx` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `idpost_UNIQUE` (`idpost` ASC) VISIBLE,
  CONSTRAINT `fk_favoritos_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `mydb`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
